import { DiningRequest, Offer, Reservation, Restaurant, UserProfile } from "./types";

export const mockUser: UserProfile = {
  id: "user-001",
  name: "홍길동",
  email: "user@golabob.kr",
  phone: "010-1234-5678",
  roles: ["user", "owner"],
  emailVerified: true,
  phoneVerified: false,
  joinedAt: "2026-07-28",
};

export const mockRequests: DiningRequest[] = [
  {
    id: "101",
    title: "강남 개발팀 회식",
    diningDate: "2026-08-28",
    diningTime: "19:00",
    headCount: 14,
    region: "강남역",
    budgetPerPerson: 55000,
    preferredMenu: "고기",
    requiredOptions: ["룸 필요", "주차 가능"],
    memo: "조용한 룸과 고기 추가 서비스가 있으면 좋겠습니다.",
    status: "open",
    createdAt: "2026-08-24T09:30:00+09:00",
  },
  {
    id: "102",
    title: "성수 디자인팀 네트워킹",
    diningDate: "2026-09-03",
    diningTime: "19:30",
    headCount: 22,
    region: "성수역",
    budgetPerPerson: 45000,
    preferredMenu: "상관없음",
    requiredOptions: ["역 근처"],
    memo: "프로젝터 사용 가능 여부를 알려주세요.",
    status: "open",
    createdAt: "2026-08-25T13:10:00+09:00",
  },
  {
    id: "103",
    title: "여의도 영업팀 월말 회식",
    diningDate: "2026-08-20",
    diningTime: "18:30",
    headCount: 10,
    region: "여의도",
    budgetPerPerson: 65000,
    preferredMenu: "일식",
    requiredOptions: ["조용한 분위기"],
    memo: "",
    status: "reserved",
    createdAt: "2026-08-12T11:00:00+09:00",
  },
];

export const mockRestaurants: Restaurant[] = [
  {
    id: "restaurant-001",
    name: "강남 화로정",
    category: "한식 · 고기",
    address: "서울 강남구 테헤란로 123",
    phone: "02-555-1001",
    businessHours: "11:30 – 23:00",
    maxCapacity: 48,
    description: "프라이빗 룸과 단체석이 준비된 한우 숯불구이 전문점입니다.",
    facilities: ["프라이빗 룸", "주차 가능", "단체석"],
    keywords: ["한식", "고기", "룸"],
    imageUris: [],
    visualColor: "#C9A98E",
    status: "approved",
    ownerId: "user-001",
  },
  {
    id: "restaurant-002",
    name: "여의도 바다한상",
    category: "일식 · 오마카세",
    address: "서울 영등포구 국제금융로 42",
    phone: "02-780-2040",
    businessHours: "11:00 – 22:00",
    maxCapacity: 32,
    description: "제철 해산물과 프라이빗 다이닝 공간을 갖춘 일식당입니다.",
    facilities: ["프라이빗 룸", "콜키지"],
    keywords: ["일식", "룸"],
    imageUris: [],
    visualColor: "#8FB8B2",
    status: "approved",
    ownerId: "owner-002",
  },
  {
    id: "restaurant-003",
    name: "서울숲 브루어리",
    category: "펍 · 양식",
    address: "서울 성동구 서울숲2길 18",
    phone: "02-466-8870",
    businessHours: "17:00 – 01:00",
    maxCapacity: 70,
    description: "수제 맥주와 단체 대관이 가능한 캐주얼 브루어리입니다.",
    facilities: ["단체석", "대관 가능"],
    keywords: ["양식", "술집"],
    imageUris: [],
    visualColor: "#AFA77A",
    status: "approved",
    ownerId: "user-001",
  },
  {
    id: "restaurant-004",
    name: "역삼 고기마당",
    category: "한식 · 고기",
    address: "서울 강남구 논현로 88",
    phone: "02-555-8844",
    businessHours: "16:00 – 24:00",
    maxCapacity: 60,
    description: "숙성 삼겹살과 넉넉한 단체석이 준비된 회식 전문점입니다.",
    facilities: ["주차 가능", "단체석"],
    keywords: ["한식", "고기"],
    imageUris: [],
    visualColor: "#B99178",
    status: "approved",
    ownerId: "owner-003",
  },
];

export const mockOffers: Offer[] = [
  {
    id: "2001",
    diningRequestId: "101",
    restaurantId: "restaurant-004",
    restaurantName: "역삼 고기마당",
    restaurantAddress: "서울 강남구 논현로 88",
    pricePerPerson: 43000,
    menuDescription: "숙성 삼겹살·목살 무제한 세트",
    serviceDescription: "소주 3병 · 볶음밥 서비스",
    seatDescription: "20인 단체석",
    availableTime: "19:00",
    ownerComment: "단독 공간으로 준비해드리겠습니다.",
    status: "pending",
    createdAt: "2026-08-25T14:00:00+09:00",
  },
  {
    id: "2002",
    diningRequestId: "101",
    restaurantId: "restaurant-002",
    restaurantName: "여의도 바다한상",
    restaurantAddress: "서울 영등포구 국제금융로 42",
    pricePerPerson: 50000,
    menuDescription: "유린기·동파육·식사 코스",
    serviceDescription: "웰컴 드링크 제공",
    seatDescription: "원형 테이블 프라이빗 룸",
    availableTime: "19:30",
    ownerComment: "조용한 룸을 우선 배정해드립니다.",
    status: "pending",
    createdAt: "2026-08-25T15:40:00+09:00",
  },
  {
    id: "2003",
    diningRequestId: "101",
    restaurantId: "restaurant-001",
    restaurantName: "강남 화로정",
    restaurantAddress: "서울 강남구 테헤란로 123",
    pricePerPerson: 52000,
    menuDescription: "한우 모둠과 된장찌개 회식 세트",
    serviceDescription: "음료 1인 1잔",
    seatDescription: "16인 프라이빗 룸",
    availableTime: "19:00",
    ownerComment: "주차 4대까지 지원합니다.",
    status: "pending",
    createdAt: "2026-08-25T17:10:00+09:00",
  },
];

export const mockReservations: Reservation[] = [
  {
    id: "reservation-001",
    restaurantId: "restaurant-001",
    restaurantName: "강남 화로정",
    reservationDate: "2026-08-28",
    reservationTime: "19:00",
    headCount: 14,
    requestMemo: "프라이빗 룸 요청",
    status: "confirmed",
    source: "offer",
    userName: "홍길동",
    userPhone: "010-1234-5678",
    createdAt: "2026-08-22T14:00:00+09:00",
  },
  {
    id: "reservation-002",
    restaurantId: "restaurant-003",
    restaurantName: "서울숲 브루어리",
    reservationDate: "2026-07-18",
    reservationTime: "18:30",
    headCount: 8,
    requestMemo: "창가 자리",
    status: "completed",
    source: "direct",
    userName: "홍길동",
    userPhone: "010-1234-5678",
    createdAt: "2026-07-10T10:20:00+09:00",
  },
  {
    id: "reservation-003",
    restaurantId: "restaurant-003",
    restaurantName: "서울숲 브루어리",
    reservationDate: "2026-09-02",
    reservationTime: "19:30",
    headCount: 18,
    requestMemo: "프로젝터 사용 문의",
    status: "pending",
    source: "direct",
    userName: "김하늘",
    userPhone: "010-9274-1138",
    createdAt: "2026-08-25T09:00:00+09:00",
  },
];
